// SPDX-License-Identifier: MIT
pragma solidity 0.8.7;

import "@chainlink/contracts/src/v0.8/KeeperCompatible.sol";
import "@openzeppelin/contracts@4.6.0/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts@4.6.0/utils/Counters.sol";

contract levelUp is ERC721, ERC721URIStorage, KeeperCompatibleInterface {
    using Counters for Counters.Counter;

    Counters.Counter public tokenIdCounter;

    // Metadata information for each stage of the NFT on IPFS.
    string[] IpfsUri = [
        "https://gateway.pinata.cloud/ipfs/QmPHyQHeipK48GUBQWohgVgyyAt3dBryfKMUL4c6ktZcr7",
        "https://gateway.pinata.cloud/ipfs/Qmd2WRzW2ryV5NZgc6EUjXR1eTyyxESSHpCNEdfPdsgtiv",
        "https://gateway.pinata.cloud/ipfs/Qmb6sidZT5KDLrQix6DNkhzVpjVCihEhujuKSYBaUBXayB",
        "https://gateway.pinata.cloud/ipfs/QmW71uYaD9eW8KsZRfiZSWTvAo3biakEUVhoyG7XTN4X4a",
        "https://gateway.pinata.cloud/ipfs/QmdM7xRSqUn4nHbDyNwd8YYTspAGDvaho9yJ1DpCA8P9kN"
    ];

    uint256 lastTimeStamp;
    uint256 interval;

    constructor(uint256 _interval) ERC721("Gamer Levels", "Gmlv") {
        interval = _interval;
        lastTimeStamp = block.timestamp;
    }

    function checkUpkeep(
        bytes calldata /* checkData */
    )
        external
        view
        override
        returns (
            bool upkeepNeeded,
            bytes memory /* performData */
        )
    {
        uint256 tokenId = tokenIdCounter.current() - 1;
        bool done;
        if (levelStage(tokenId) >= 5) {
            done = true;
        }

        upkeepNeeded = !done && ((block.timestamp - lastTimeStamp) > interval);
        // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered.
    }

    function performUpkeep(
        bytes calldata /* performData */
    ) external override {
        //We highly recommend revalidating the upkeep in the performUpkeep function
        if ((block.timestamp - lastTimeStamp) > interval) {
            lastTimeStamp = block.timestamp;
            uint256 tokenId = tokenIdCounter.current() - 1;
            gamerLevelUp(tokenId);
        }
        // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
    }

    function safeMint(address to) public {
        uint256 tokenId = tokenIdCounter.current();
        tokenIdCounter.increment();
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, IpfsUri[0]);
    }

    function gamerLevelUp(uint256 _tokenId) public {
        if (levelStage(_tokenId) >= 5) {
            return;
        }
        // Get the current stage of the flower and add 1
        uint256 newVal = levelStage(_tokenId) + 1;
        // store the new URI
        string memory newUri = IpfsUri[newVal];
        // Update the URI
        _setTokenURI(_tokenId, newUri);
    }

    // determine the stage of the flower growth
    function levelStage(uint256 _tokenId) public view returns (uint256) {
        string memory _uri = tokenURI(_tokenId);
        // Seed
        if (compareStrings(_uri, IpfsUri[0])) {
            return 0;
        }
        // Sprout
        if (compareStrings(_uri, IpfsUri[1])) {
            return 1;
        }
        if (compareStrings(_uri, IpfsUri[2])) {
            return 2;
        }
        if (compareStrings(_uri, IpfsUri[3])) {
            return 3;
        }
        if (compareStrings(_uri, IpfsUri[4])) {
            return 4;
        }
        // Must be a Bloom
        return 5;
    }

    // helper function to compare strings
    function compareStrings(string memory a, string memory b)
        public
        pure
        returns (bool)
    {
        return (keccak256(abi.encodePacked((a))) ==
            keccak256(abi.encodePacked((b))));
    }

    // The following functions is an override required by Solidity.
    function _burn(uint256 tokenId)
        internal
        override(ERC721, ERC721URIStorage)
    {
        super._burn(tokenId);
    }

    // The following functions is an override required by Solidity.
    function tokenURI(uint256 tokenId)
        public
        view
        override(ERC721, ERC721URIStorage)
        returns (string memory)
    {
        return super.tokenURI(tokenId);
    }
}
//End
